backend:
  name: github
  repo: Eeleenaa21/gestalt.bartosh.org
  branch: master
  base_url: https://gestalt-cms-auth.onrender.com
  auth_endpoint: /api/auth

media_folder: "static/images"
public_folder: "/images"

site_url: https://test.bartosh.org/
logo_url: /images/photo.png

collections:
  - name: "home"
    label: "Главная страница"
    files:
      - file: "content/_index.md"
        label: "Главная страница"
        name: "home_file"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Содержимое", name: "body", widget: "markdown" }

  - name: "about"
    label: "Страница «Обо мне»"
    files:
      - file: "content/obo-mne/_index.md"
        label: "Страница «Обо мне»"
        name: "about_file"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Содержимое", name: "body", widget: "markdown" }

  - name: "stati"
    label: "Статьи"
    folder: "content/stati"
    create: true
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Содержимое", name: "body", widget: "markdown" }